function coordinates = import_force_curve_txt_file_fast(filename, startRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   coordinates = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
% 
%   -> coordinates is a struct with the fields x_values and y_values each
%      containing the vector of the corresponding force curve coordinate.
%
%   coordinates = IMPORTFILE(FILENAME, STARTROW) Reads data
%   from rows STARTROW through end of text file FILENAME.
%
% Example:
%   coordinates = importfile('map-data-2018.03.07-10.39.13.034_00.txt',16, 4946);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/08/19 11:13:39

%% Initialize variables.
delimiter = ' ';
if nargin<2
    startRow = 16;
end
endRow = inf;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
coordinates = struct;
coordinates.x_values = dataArray{:, 1};
coordinates.y_values = dataArray{:, 2};


